#!/bin/bash


TOPOFILE=
SCRIPTFILE=

while [ "$#" -gt "0" ]
do

if [ "$1" = "--topo" ]; then
	TOPOFILE=$2
	shift 2

elif [ "$1" = "--script" ]; then
	SCRIPTFILE=$2
	shift 2

else
	echo "Usage:"
	echo "den [--topo topofile] [--script scriptfile]"
        echo ""
	exit 1
fi

done

fab up:topo=$TOPOFILE,script=$SCRIPTFILE
